// <auto-generated />
using System;
using CGTOOL.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CGTOOL.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801215659_AddNavMenuItemOrder")]
    partial class AddNavMenuItemOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGTOOL.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActingOnBehalfOf")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiCompanyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoiRelativeId")
                        .HasColumnType("int");

                    b.Property<string>("LegalCompanyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("LicenseActivities")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<string>("PrincipalBusinessActivity")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("RelatedPartyCoiDeclarationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TradeLicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TradeLicenseNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CoiRelativeId");

                    b.HasIndex("RelatedPartyCoiDeclarationId");

                    b.ToTable("CoiCompanyEntries");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiConflictEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyOrCounterpartyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NatureOfHolding")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PrincipalBusinessActivity")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("RelatedPartyCoiDeclarationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPartyCoiDeclarationId");

                    b.ToTable("CoiConflictEntries");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiRelative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RelatedPartyCoiDeclarationId")
                        .HasColumnType("int");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPartyCoiDeclarationId");

                    b.ToTable("CoiRelatives");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiTradeLicenseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoiCompanyEntryId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoiCompanyEntryId");

                    b.ToTable("CoiTradeLicenseDocuments");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int?>("ApprovingAuthorityMemberId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("DelegateAuthorityMemberId")
                        .HasColumnType("int");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingAuthorityMemberId");

                    b.HasIndex("DelegateAuthorityMemberId");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationCycleRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DeclarationCycleSetupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReminderSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodQuarter")
                        .HasColumnType("int");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("int");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("int");

                    b.Property<int>("RemindersSent")
                        .HasColumnType("int");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeclarationCycleSetupId");

                    b.ToTable("DeclarationCycleRuns");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationCycleRunRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("DeclarationCycleRunId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationCycleRunId");

                    b.ToTable("DeclarationCycleRunRecipients");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationCycleSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int");

                    b.Property<int>("ReminderFrequency")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("DeclarationCycleSetups");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastReminderSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclarationSetups");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeclarationSetupId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationSetupId");

                    b.HasIndex("MemberId", "DeclarationSetupId")
                        .IsUnique();

                    b.ToTable("DeclarationSubmissions");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeclarationCycleRunId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmiratesIdExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmiratesIdNameOnCard")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EmiratesIdNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EmiratesIdPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("HasNin")
                        .HasColumnType("bit");

                    b.Property<bool>("HoldsShares")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NinNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("NumberOfSharesHeld")
                        .HasColumnType("int");

                    b.Property<string>("OtherDocumentPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime?>("PassportExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportIssuingCountry")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PassportPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("RelativesHaveNin")
                        .HasColumnType("bit");

                    b.Property<bool>("RelativesHoldShares")
                        .HasColumnType("bit");

                    b.Property<string>("SharesNinNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("SubmittedOnBehalfOf")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("TradeLicenceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TradeLicenceIssuingAuthority")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("TradeLicenceLegalName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("TradeLicenceNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TradeLicencePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationCycleRunId");

                    b.HasIndex("MemberId", "DeclarationCycleRunId")
                        .IsUnique();

                    b.ToTable("InsiderDeclarations");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclarationNinHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("InsiderDeclarationId")
                        .HasColumnType("int");

                    b.Property<string>("NameOfShareHolder")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NinNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsiderDeclarationId");

                    b.ToTable("InsiderDeclarationNinHolders");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclarationRelative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("InsiderDeclarationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelf")
                        .HasColumnType("bit");

                    b.Property<string>("NinNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("NumberOfShares")
                        .HasColumnType("int");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<string>("RelativeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("InsiderDeclarationId");

                    b.ToTable("InsiderDeclarationRelatives");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AzureAdObjectId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("CanBeImpersonated")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("ConflictOfInterestAccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("InsiderTradingAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBoardMember")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExecutiveManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternalMember")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManualEntry")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RelatedPartyRegisterAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("RelatedPartyTransactionAccess")
                        .HasColumnType("bit");

                    b.Property<int?>("ReportingManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ReportingManagerId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.MemberImpersonationApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImpersonatorId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImpersonatorId");

                    b.HasIndex("MemberId", "ImpersonatorId")
                        .IsUnique();

                    b.ToTable("MemberImpersonationApprovals");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.MemberNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("Status");

                    b.ToTable("MemberNotifications");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.NavMenuItemOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemKey")
                        .IsUnique();

                    b.ToTable("NavMenuItemOrders");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.PolicyDocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("PolicyDocumentVersions");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.RelatedPartyCoiDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttestationConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("AttestationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("DeclarationCycleRunId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NothingToDeclareBoardRoles")
                        .HasColumnType("bit");

                    b.Property<bool>("NothingToDeclareConflicts")
                        .HasColumnType("bit");

                    b.Property<bool>("NothingToDeclareRelativeOwned")
                        .HasColumnType("bit");

                    b.Property<bool>("NothingToDeclareRelatives")
                        .HasColumnType("bit");

                    b.Property<bool>("NothingToDeclareSelfOwned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("SubmittedOnBehalfOf")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("UaePassUuid")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UaePassVerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UaePassVerifiedName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationCycleRunId");

                    b.HasIndex("MemberId");

                    b.ToTable("RelatedPartyCoiDeclarations");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.ScheduledActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScheduledActivities");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.ScheduledActivityDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastTriggeredUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("ScheduledActivityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledActivityId", "Month", "Day")
                        .IsUnique();

                    b.ToTable("ScheduledActivityDates");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ComplianceNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("FiledDate")
                        .HasColumnType("date");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyReference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reviewer")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiCompanyEntry", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.CoiRelative", "CoiRelative")
                        .WithMany()
                        .HasForeignKey("CoiRelativeId");

                    b.HasOne("CGTOOL.Web.Data.Governance.RelatedPartyCoiDeclaration", "RelatedPartyCoiDeclaration")
                        .WithMany("Companies")
                        .HasForeignKey("RelatedPartyCoiDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoiRelative");

                    b.Navigation("RelatedPartyCoiDeclaration");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiConflictEntry", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.RelatedPartyCoiDeclaration", "RelatedPartyCoiDeclaration")
                        .WithMany("Conflicts")
                        .HasForeignKey("RelatedPartyCoiDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedPartyCoiDeclaration");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiRelative", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.RelatedPartyCoiDeclaration", "RelatedPartyCoiDeclaration")
                        .WithMany("Relatives")
                        .HasForeignKey("RelatedPartyCoiDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedPartyCoiDeclaration");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiTradeLicenseDocument", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.CoiCompanyEntry", "CoiCompanyEntry")
                        .WithMany("Documents")
                        .HasForeignKey("CoiCompanyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoiCompanyEntry");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Company", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "ApprovingAuthorityMember")
                        .WithMany()
                        .HasForeignKey("ApprovingAuthorityMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "DelegateAuthorityMember")
                        .WithMany()
                        .HasForeignKey("DelegateAuthorityMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovingAuthorityMember");

                    b.Navigation("DelegateAuthorityMember");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationCycleRun", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CGTOOL.Web.Data.Governance.DeclarationCycleSetup", "DeclarationCycleSetup")
                        .WithMany()
                        .HasForeignKey("DeclarationCycleSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DeclarationCycleSetup");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationCycleRunRecipient", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.DeclarationCycleRun", "DeclarationCycleRun")
                        .WithMany("Recipients")
                        .HasForeignKey("DeclarationCycleRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeclarationCycleRun");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationSubmission", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.DeclarationSetup", "DeclarationSetup")
                        .WithMany()
                        .HasForeignKey("DeclarationSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeclarationSetup");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclaration", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.DeclarationCycleRun", "DeclarationCycleRun")
                        .WithMany()
                        .HasForeignKey("DeclarationCycleRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeclarationCycleRun");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclarationNinHolder", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.InsiderDeclaration", "InsiderDeclaration")
                        .WithMany("NinHolders")
                        .HasForeignKey("InsiderDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsiderDeclaration");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclarationRelative", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.InsiderDeclaration", "InsiderDeclaration")
                        .WithMany("Relatives")
                        .HasForeignKey("InsiderDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsiderDeclaration");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Member", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CGTOOL.Web.Data.Governance.Company", "Company")
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGTOOL.Web.Data.Governance.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "ReportingManager")
                        .WithMany()
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("ReportingManager");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.MemberImpersonationApproval", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Impersonator")
                        .WithMany()
                        .HasForeignKey("ImpersonatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Member")
                        .WithMany("ApprovedImpersonators")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impersonator");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.MemberNotification", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.RelatedPartyCoiDeclaration", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.DeclarationCycleRun", "DeclarationCycleRun")
                        .WithMany()
                        .HasForeignKey("DeclarationCycleRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeclarationCycleRun");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.ScheduledActivityDate", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.ScheduledActivity", "ScheduledActivity")
                        .WithMany("Dates")
                        .HasForeignKey("ScheduledActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledActivity");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Transaction", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.Governance.Member", "Member")
                        .WithMany("Transactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGTOOL.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CGTOOL.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.CoiCompanyEntry", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Company", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.DeclarationCycleRun", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Department", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.InsiderDeclaration", b =>
                {
                    b.Navigation("NinHolders");

                    b.Navigation("Relatives");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.Member", b =>
                {
                    b.Navigation("ApprovedImpersonators");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.RelatedPartyCoiDeclaration", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Conflicts");

                    b.Navigation("Relatives");
                });

            modelBuilder.Entity("CGTOOL.Web.Data.Governance.ScheduledActivity", b =>
                {
                    b.Navigation("Dates");
                });
#pragma warning restore 612, 618
        }
    }
}
