SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @Titles TABLE ([Name] NVARCHAR(120) NOT NULL);

INSERT INTO @Titles ([Name])
VALUES
    (N'Manager - Operations'),
    (N'Sr. Systems Administrator'),
    (N'Vice Chairman & CEO'),
    (N'Chief Operating Officer (COO)'),
    (N'General Manager'),
    (N'IT Support Engineer'),
    (N'System Administrator'),
    (N'Manager - Business Applications'),
    (N'Associate Director - ERP'),
    (N'Manager – Master Data Management'),
    (N'Head of Projects - Real Estate platform'),
    (N'Deputy GM - Commercial'),
    (N'Sr. Sales & Marketing Executive'),
    (N'Project Manager'),
    (N'Assistant Manager -Tenant Relation'),
    (N'Engineering Secretary'),
    (N'Team Leader'),
    (N'Deputy GM - Operations'),
    (N'Team Leader – Revenue Dpt'),
    (N'Executive assistant – GM’s Office'),
    (N'Asistant Manager – Finance'),
    (N'Assistant – Commercial Dept'),
    (N'Commercial Manager'),
    (N'Investments Director'),
    (N'Office Manager'),
    (N'Store Keeper'),
    (N'Senior Projects Manager'),
    (N'HR Generalist'),
    (N'Project Coordinator'),
    (N'Sr.Accountant'),
    (N'Procurement Executive'),
    (N'Project Engineer'),
    (N'DGM'),
    (N'Executive Secretary'),
    (N'Production Control Supervisor'),
    (N'QA/QC Engineer'),
    (N'Sales Manager - Dubai'),
    (N'Group Public Relations Manager'),
    (N'Accounts Manager'),
    (N'Sr. Officer - Government Affairs'),
    (N'Public Relations Administrator'),
    (N'Manager – Marketing'),
    (N'Manager - Shares'),
    (N'Director - Group Marketing & Communications'),
    (N'Manager – Sustainability'),
    (N'Assistant Manager – Finance'),
    (N'Chief Internal Audit Officer'),
    (N'Senior PR Administrator'),
    (N'Assistant Manager – IA Operations'),
    (N'Deputy General Manager'),
    (N'Associate Sales Director'),
    (N'Supply Chain Analyst'),
    (N'CEO Glass LLC'),
    (N'Sr. Detailer'),
    (N'Sr. Checker'),
    (N'Detailer'),
    (N'QA/QC – Document Controller'),
    (N'Quantitative survivor'),
    (N'Checker'),
    (N'Accounts Clerk'),
    (N'Logistics Officer'),
    (N'Sr. PR Officer'),
    (N'Project Cum Procurement Officer'),
    (N'Sr. Revenue Executive'),
    (N'Sr. Landscaping Engineer'),
    (N'Senior Legal Adviser'),
    (N'IT Support Assistant'),
    (N'Chief Human Resources & Administration Officer'),
    (N'Sr. Projects Manager'),
    (N'Procurement Assistant'),
    (N'Technical & Design Head'),
    (N'Sr. Administration Officer'),
    (N'Assistant Manager - Account'),
    (N'Sr. Property Executive'),
    (N'Property Supervisor'),
    (N'Director - Group HR'),
    (N'Associate Director – Internal Audit'),
    (N'Senior Property Manager'),
    (N'Production Manager'),
    (N'Sr. Security Manager'),
    (N'Property Executive'),
    (N'Chief Accountant'),
    (N'Designer'),
    (N'Supply Chain Manager'),
    (N'Finance Manager'),
    (N'Procurement Officer'),
    (N'Admin Clerk'),
    (N'QC/QA Supervisor'),
    (N'Sr Design & Estimation Engineer'),
    (N'Design & Estimation Manager'),
    (N'Site Inspector'),
    (N'Assistant Manager-HR'),
    (N'Sr. Executive Assistant & Facility Officer'),
    (N'Head of Compliance'),
    (N'Administration Officer'),
    (N'Fabrication Supervisor'),
    (N'Office Clerk'),
    (N'Assistant Manager Landscape'),
    (N'Gym Supervisor'),
    (N'Manager – Group Human Resources'),
    (N'Head of Operations'),
    (N'Secretary'),
    (N'Maintenance'),
    (N'Sales Coordinator'),
    (N'Quality'),
    (N'Dispatcher'),
    (N'Secretary cum AutoCAD Officer'),
    (N'Testing Administrator'),
    (N'Sr. Tenant Relation Executive'),
    (N'Senior Accountant'),
    (N'Sr. Manager - Portfolio Management'),
    (N'Design & Estimation Engineer'),
    (N'Sales Manager'),
    (N'Production In charge'),
    (N'Accountant'),
    (N'Site Supervisor'),
    (N'Planner'),
    (N'Team Lead – IT Support'),
    (N'Senior Manager - Internal Audit'),
    (N'Business Center Executive'),
    (N'Office Administrator-Ritaj'),
    (N'Assistant Finance Manager'),
    (N'Assistant Manager - IT'),
    (N'Optimization Assistant'),
    (N'info'),
    (N'Supervisor Flat Lamination'),
    (N'Technical Designer'),
    (N'Invoicing Clerk'),
    (N'HSE Assistant'),
    (N'Assistant Manager - Production'),
    (N'Senior Supervisor - Health & Safety'),
    (N'QC Inspector'),
    (N'Estimation'),
    (N'Customer Service - Co-ordinator'),
    (N'Senior Optimizer'),
    (N'Debit Controller Executive'),
    (N'Senior Workorder Executive'),
    (N'Customer Service'),
    (N'Vice President - Operations'),
    (N'PRO/Service Manager'),
    (N'Manager-Planning&Optimization'),
    (N'Assistant Manager - Finance'),
    (N'Executive President'),
    (N'Logistics Coordinator'),
    (N'Senior Manager -Sales'),
    (N'Senior Vice president Sales & Marketing'),
    (N'Mall Manager'),
    (N'Senior Supervisor - Production & Planning'),
    (N'Senior Dispatch Supervisor'),
    (N'CFO-Industrial Platform'),
    (N'Manager Sales - BRG'),
    (N'Assistant Manager - Sales'),
    (N'Projects Engineer'),
    (N'Document Controller'),
    (N'Estimator'),
    (N'Site Inspector cum Electrician'),
    (N'Tekla Detailer'),
    (N'Sales Representative'),
    (N'Senior Manager – VC/CEO Office'),
    (N'Admin Assistant'),
    (N'Sr. Systems & Products Dev. Specialist'),
    (N'Executive Assistant & Project Officer'),
    (N'Sr. Design & Estimation Engineer'),
    (N'EGL- Maintenance'),
    (N'Maintenance Manager'),
    (N'Chief Financial Officer'),
    (N'Assistant Manager - PR & Media'),
    (N'Vat Accountant'),
    (N'Asst Accountant'),
    (N'Maintenance Engineer'),
    (N'Machine Operator'),
    (N'Computer Operator'),
    (N'IT Technical Support'),
    (N'Sales & Marketing Africa'),
    (N'Assistant Manager Finance'),
    (N'Assistant Sales Manager'),
    (N'Manager - Estimation'),
    (N'Receptionist'),
    (N'Sr. Operations Manager'),
    (N'Relationship Manager'),
    (N'Government Affairs'),
    (N'Admin Officer'),
    (N'Campboss'),
    (N'Special Projects – Sr. Manager'),
    (N'LGI - Maintenance'),
    (N'Area Sales Manager (Ivory Coast & Ghana)'),
    (N'Production Supervisor'),
    (N'Accountant - AP'),
    (N'Sr. Sales and Leasing Executive'),
    (N'Accountant - AR & Banking'),
    (N'Site/Erection Supervisor'),
    (N'Lead Developer'),
    (N'Leasing Consultant'),
    (N'Sr. OA Manager'),
    (N'HR & Admin'),
    (N'Legal Advisor'),
    (N'NDT Inspector'),
    (N'Sr. Shipping Supervisor'),
    (N'Technical Facility Manager .'),
    (N'Information Security Manager'),
    (N'Industrial Engineer'),
    (N'Sr. Network Security Engineer'),
    (N'Compliance Supervisor'),
    (N'Sr. Credit Controller'),
    (N'Assistant Vice President'),
    (N'Quality Controller'),
    (N'PR Administrator'),
    (N'Sr. Administrative Officer'),
    (N'Senior Finance Manager'),
    (N'Senior Planner'),
    (N'Executive Secretary to the CEO - Glass LLC'),
    (N'Network & Security Engineer'),
    (N'Purchase officer'),
    (N'Leasing Manager'),
    (N'Retail Coordinator'),
    (N'ERP Project Manager'),
    (N'Logistic Coordinator'),
    (N'Sales Executive'),
    (N'Facility Engineer'),
    (N'Sr. Accountant'),
    (N'Procurement Manager'),
    (N'Sales & Marketing Ethiopia'),
    (N'Legal secretary'),
    (N'Supervisor - Production'),
    (N'Procurement Supervisor'),
    (N'Director - Mall Operations & Leasing'),
    (N'Admin. Executive'),
    (N'Sr. Administrator'),
    (N'Dispatch Coordinator'),
    (N'Administrator'),
    (N'HR and Admin Manager'),
    (N'Dieshop Supervisor'),
    (N'Portfolio Officer'),
    (N'Operation Manager'),
    (N'Warehouse Assistant'),
    (N'HR & Admin Manager'),
    (N'Assistant HR Manager'),
    (N'Assistant Manager – Talent Acquisition'),
    (N'Area Sales Manager – Central Asia, Uzbekistan'),
    (N'HR Manager'),
    (N'Executive Assistant'),
    (N'HR & Admin Officer'),
    (N'Telesales Executive'),
    (N'Legal Associate'),
    (N'Senior Associate Digital Marketing'),
    (N'Sales Admin Manager'),
    (N'HR Officer'),
    (N'Technical Supervisor'),
    (N'HR Administrative Assistant'),
    (N'Collection Supervisor'),
    (N'Design Executive'),
    (N'Software Programmer / Oracle Developer'),
    (N'Assistant Manager - Internal Audit'),
    (N'Contract Manager'),
    (N'Chief Information Officer'),
    (N'Regional Sales Manager'),
    (N'Mech. Draftsman'),
    (N'Senior Administrative Officer'),
    (N'IT Associate'),
    (N'Collection Officer'),
    (N'Oracle Fusion -Technical Consultant'),
    (N'Sales  Coordinator'),
    (N'QC engineer'),
    (N'Community Associate'),
    (N'Sr. Internal Auditor'),
    (N'Business Development Manager'),
    (N'Façade Architecture Advisor'),
    (N'Manager – Investor Relations'),
    (N'Sr. Legal Associate'),
    (N'Procurement'),
    (N'Mechanical Draftsman'),
    (N'Chemist'),
    (N'Facility Supervisor MEP'),
    (N'Head of Projects – Real Estate Platform'),
    (N'Administrative Officer'),
    (N'Security'),
    (N'Sr. Construction Manager'),
    (N'Draftsman'),
    (N'Lead Developer (.NET)'),
    (N'Head of Finance'),
    (N'Collection In Charge'),
    (N'Sr. Commercial Manager'),
    (N'Sales Admin'),
    (N'Office Administrator'),
    (N'Senior Tax Manager'),
    (N'FM- Admin'),
    (N'Sales Support Engineer'),
    (N'Oracle Fusion-CX Consultant'),
    (N'Sr. Administrative Officer - Projects'),
    (N'Facility Manager'),
    (N'Superintendent Villas'),
    (N'Marketing Executive'),
    (N'Cost Accountant'),
    (N'Data Entry Personnel'),
    (N'HSE Officer'),
    (N'Projects / Site Engineer'),
    (N'Data Entry Personel'),
    (N'IT Assistant'),
    (N'Graphic Designer'),
    (N'Data Entry Operator'),
    (N'Emiratization Specialist'),
    (N'Front Office Coordinator'),
    (N'Assistant Manager- Marketing and Specification'),
    (N'Design Engineer'),
    (N'Assistant Manager - Risk'),
    (N'Head of Risk'),
    (N'Assistant Manager – QA/QC'),
    (N'PRO'),
    (N'Finance Executive'),
    (N'Senior Operations Manager'),
    (N'Financial Analyst'),
    (N'Oracle Fusion – HCM Consultant'),
    (N'Dispatcher Forman'),
    (N'Warehouse Executive'),
    (N'Assistant Manager-Finance'),
    (N'Administrative Assistant'),
    (N'Leasing Director'),
    (N'General Manager Sales & Marketing'),
    (N'Superintendent'),
    (N'Public Relation Officer'),
    (N'Sr.Detailer'),
    (N'Admin. Assitant'),
    (N'Chief Corporate Affairs Officer'),
    (N'Assistant Manager- Production'),
    (N'Collection'),
    (N'Production Administrative Coordinator (Plant)'),
    (N'Sales Assistant'),
    (N'Senior HAVAC Technician'),
    (N'Tax Analyst'),
    (N'Engineering Supervisor'),
    (N'Civil Technician'),
    (N'Senior Checker'),
    (N'Plumber'),
    (N'Brand Marketing Executive'),
    (N'Buyer'),
    (N'Warehouse Supervisor'),
    (N'Asst. Designer'),
    (N'Sr.Finance Manager'),
    (N'Estimation Coordinator'),
    (N'Admin. Officer'),
    (N'Investment Manager'),
    (N'Legal Trainee'),
    (N'Logistics Supervisor'),
    (N'Planning Officer'),
    (N'Technical Engineer'),
    (N'Senior Sales Manager'),
    (N'Supervisor'),
    (N'Financial Controller'),
    (N'Cashier'),
    (N'Expeditor'),
    (N'MEP Supervisor'),
    (N'Operator'),
    (N'Storekeeper'),
    (N'QA & QC Inspector'),
    (N'Front Office Cooedinator'),
    (N'Security Guard'),
    (N'Expidator'),
    (N'Junior Accountant'),
    (N'Group General Counsel'),
    (N'Sr. Development Manager'),
    (N'Senior Project Engineer'),
    (N'Electrician'),
    (N'Customer Service Executive'),
    (N'Community Admin'),
    (N'Assistant Manager ERP'),
    (N'IT Support Administrator'),
    (N'Senior Operation Manager'),
    (N'Community Service Executive'),
    (N'IT Coordinator'),
    (N'Sr. Project Engineer'),
    (N'Technical Executive'),
    (N'Plant Manager'),
    (N'Safety Officer'),
    (N'Assistant Storekeeper'),
    (N'Lab. Chemist'),
    (N'Generic Email (Production)'),
    (N'Marketing & Specification Manager'),
    (N'Business Development Executive'),
    (N'Sales Engineer'),
    (N'Purchase Manager'),
    (N'Storekeeper Assistant'),
    (N'Executive Assistant & Financial Coordinator'),
    (N'Assistant Accountant'),
    (N'Painting Inspector'),
    (N'Sales Support'),
    (N'Technical Support Manager'),
    (N'Senior HR & Admin Executive'),
    (N'Intern'),
    (N'Assistant Supervisor - Production'),
    (N'Material Movement Operator'),
    (N'Die Shop Supervisor'),
    (N'Data Entry Officer'),
    (N'Revenue Executive'),
    (N'Portfolio Manager'),
    (N'Security & Facility Supervisor'),
    (N'Senior Design Engineer'),
    (N'Senior Detailer'),
    (N'HSE'),
    (N'Legal Assistant'),
    (N'Packing Forman'),
    (N'Anodizing Forman'),
    (N'Powder Coating Forman'),
    (N'Press Operator'),
    (N'Senior Sales Executive'),
    (N'Manager Internal Audit'),
    (N'Sr. Marketing Manager'),
    (N'HR & Payroll Officer'),
    (N'Sr. Design Engineer'),
    (N'Receptionist cum Admin'),
    (N'Planning Engineer'),
    (N'MCA Consultant'),
    (N'HR/Marketing cum Administration Manager'),
    (N'Internal Auditor'),
    (N'HR Administrator'),
    (N'HR Assistant'),
    (N'Production Planning Officer'),
    (N'Hand-Over Officer'),
    (N'Country Manager'),
    (N'AML Focal Point'),
    (N'HOA Manager'),
    (N'Senior Maintenance Engineer'),
    (N'Storekeeper Assit'),
    (N'Projects Manager'),
    (N'HSE Manager'),
    (N'Sr. Executive -Warehouse & Inventory'),
    (N'Production Planning Engineer'),
    (N'Inventory Controller'),
    (N'Executive VP Sales and Operation'),
    (N'Senior QC Engineer'),
    (N'CFO'),
    (N'Assistant Manager – Sales - Digital Printing'),
    (N'Senior Design & Estimation Engineer'),
    (N'ERP Programmer Analyst'),
    (N'Sales Representative - Africa'),
    (N'Business Analyst'),
    (N'Civil Tech'),
    (N'MDM Officer'),
    (N'Quality Officer'),
    (N'Investment Analyst'),
    (N'Marketing and Coordination Executive'),
    (N'Compliance Officer'),
    (N'Executive Assistant - COO'),
    (N'Head of Security'),
    (N'Consultant'),
    (N'Site Security'),
    (N'Sr Production Supervisor'),
    (N'IT Project Coordinator'),
    (N'Oracle Fusion - Finance Consultant'),
    (N'Temporary Business Center Executive'),
    (N'Internship'),
    (N'HR/Admin Executive'),
    (N'Facility Admin'),
    (N'Estimation Engineer'),
    (N'Sr. Compliance Officer'),
    (N'Receptionist Ground Floor'),
    (N'Risk Administrator'),
    (N'Leasing Officer'),
    (N'QC Supervisor'),
    (N'Project Accountant'),
    (N'Sr. Tax Analyst'),
    (N'EPM Consultant');

-- Insert only titles not already present (trimmed, de-duplicated)
INSERT INTO [dbo].[JobTitles] ([Name], [Active])
SELECT DISTINCT LTRIM(RTRIM(t.[Name])), 1
FROM @Titles t
WHERE NOT EXISTS (
    SELECT 1
    FROM [dbo].[JobTitles] j
    WHERE j.[Name] = LTRIM(RTRIM(t.[Name]))
);

SELECT @@ROWCOUNT AS RowsInserted;

COMMIT TRANSACTION;
GO