SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @Departments TABLE (
    [Code] NVARCHAR(20)  NOT NULL,
    [Name] NVARCHAR(120) NOT NULL
);

INSERT INTO @Departments ([Code], [Name])
VALUES
    (N'DEPT001', N'TS Technology & Operations'),
    (N'DEPT002', N'DI Corporate Finance'),
    (N'DEPT003', N'Administration'),
    (N'DEPT004', N'TS Business Systems'),
    (N'DEPT005', N'TS Digital Transformation'),
    (N'DEPT006', N'Engineering'),
    (N'DEPT007', N'MARKETING'),
    (N'DEPT008', N'Tenant’s Relation'),
    (N'DEPT009', N'Revenue Department'),
    (N'DEPT010', N'Engineering Department'),
    (N'DEPT011', N'Accounts'),
    (N'DEPT012', N'Leasing'),
    (N'DEPT013', N'DII Operations'),
    (N'DEPT014', N'DII Administration'),
    (N'DEPT015', N'Warehouse & Inventory'),
    (N'DEPT016', N'Customer Service'),
    (N'DEPT017', N'HR'),
    (N'DEPT018', N'Projects'),
    (N'DEPT019', N'Finance'),
    (N'DEPT020', N'PURCHASING'),
    (N'DEPT021', N'Gm''s Office'),
    (N'DEPT022', N'Production Control'),
    (N'DEPT023', N'QA/QC'),
    (N'DEPT024', N'DI Group Public Relations'),
    (N'DEPT025', N'DI Group Marketing'),
    (N'DEPT026', N'DI Corporate Affairs'),
    (N'DEPT027', N'DI Group Internal Audit'),
    (N'DEPT028', N'DIRC Management'),
    (N'DEPT029', N'DIRC Property Management'),
    (N'DEPT030', N'Production'),
    (N'DEPT031', N'DI Management'),
    (N'DEPT032', N'Engg'),
    (N'DEPT033', N'Logistics'),
    (N'DEPT034', N'Revenue Dept.'),
    (N'DEPT035', N'DI Group HR and Admin'),
    (N'DEPT036', N'DIRC Engineering'),
    (N'DEPT037', N'DIRC HR & Admin'),
    (N'DEPT038', N'DIRC Finance'),
    (N'DEPT039', N'Ritaj - Property Management'),
    (N'DEPT040', N'DIRC Leasing'),
    (N'DEPT041', N'Property Management'),
    (N'DEPT042', N'Al Mujama Owner Association'),
    (N'DEPT043', N'Sales'),
    (N'DEPT044', N'Supply chain'),
    (N'DEPT045', N'Store'),
    (N'DEPT046', N'Estimation'),
    (N'DEPT047', N'DII Management'),
    (N'DEPT048', N'Internal Audit & Compliance'),
    (N'DEPT049', N'DIP Admin'),
    (N'DEPT050', N'DIRC Admin'),
    (N'DEPT051', N'Gym'),
    (N'DEPT052', N'Operations'),
    (N'DEPT053', N'Maintenance'),
    (N'DEPT054', N'Quality Control'),
    (N'DEPT055', N'Resigned'),
    (N'DEPT056', N'Planning'),
    (N'DEPT057', N'Business Development'),
    (N'DEPT058', N'IT'),
    (N'DEPT059', N'Finance & Accounting'),
    (N'DEPT060', N'QC / QC'),
    (N'DEPT061', N'QC'),
    (N'DEPT062', N'Finance & Account'),
    (N'DEPT063', N'HR & Admin'),
    (N'DEPT064', N'PPC'),
    (N'DEPT065', N'Management'),
    (N'DEPT066', N'General Management'),
    (N'DEPT067', N'Sales & Marketing'),
    (N'DEPT068', N'Sales & Leasing'),
    (N'DEPT069', N'DI CEO Office'),
    (N'DEPT070', N'TS Management'),
    (N'DEPT071', N'Ritaj-Security Guard'),
    (N'DEPT072', N'DIRC Legal'),
    (N'DEPT073', N'Property Management Mirdif Hills'),
    (N'DEPT074', N'DI Operations - Industrial Platform'),
    (N'DEPT075', N'Commercial'),
    (N'DEPT076', N'Finance and accounting'),
    (N'DEPT077', N'Erection'),
    (N'DEPT078', N'DI Group Legal'),
    (N'DEPT079', N'Shipping'),
    (N'DEPT080', N'TS Information Security'),
    (N'DEPT081', N'External'),
    (N'DEPT082', N'Quality'),
    (N'DEPT083', N'Stores'),
    (N'DEPT084', N'Mirdif-Sales'),
    (N'DEPT085', N'Purchase'),
    (N'DEPT086', N'Despatch'),
    (N'DEPT087', N'Property & Facility Management'),
    (N'DEPT088', N'Procurement'),
    (N'DEPT089', N'Legal'),
    (N'DEPT090', N'PID'),
    (N'DEPT091', N'Dispatch'),
    (N'DEPT092', N'Facility Management'),
    (N'DEPT093', N'Dieshop'),
    (N'DEPT094', N'Inventory'),
    (N'DEPT095', N'PM- leasing department'),
    (N'DEPT096', N'Credit Risk & Collection'),
    (N'DEPT097', N'Design'),
    (N'DEPT098', N'Finance & Admin'),
    (N'DEPT099', N'Marketing & Specification'),
    (N'DEPT100', N'PM- leasing deaprtment'),
    (N'DEPT101', N'Property & Facility  Management'),
    (N'DEPT102', N'Finance & Accounts'),
    (N'DEPT103', N'HSE'),
    (N'DEPT104', N'CSD'),
    (N'DEPT105', N'DI Risk'),
    (N'DEPT106', N'Finance - Collection'),
    (N'DEPT107', N'DI Compliance'),
    (N'DEPT108', N'DIFC'),
    (N'DEPT109', N'Community Management'),
    (N'DEPT110', N'QAQC/TECHNICAL DEPARTMENT'),
    (N'DEPT111', N'Lab'),
    (N'DEPT112', N'DII Finance'),
    (N'DEPT113', N'Admin'),
    (N'DEPT114', N'Die Shop'),
    (N'DEPT115', N'Commercial - TR'),
    (N'DEPT116', N'Packing'),
    (N'DEPT117', N'Anodizing'),
    (N'DEPT118', N'Powder Coating'),
    (N'DEPT119', N'TS'),
    (N'DEPT120', N'HR/Marketing/Administration'),
    (N'DEPT121', N'CRM'),
    (N'DEPT122', N'HR&Admin'),
    (N'DEPT123', N'Safety Dept.'),
    (N'DEPT124', N'Maintenance Dept.'),
    (N'DEPT125', N'DI - Internal Audit'),
    (N'DEPT126', N'Assistant PRO'),
    (N'DEPT127', N'MSH - ERB'),
    (N'DEPT128', N'Al Taif Business Center'),
    (N'DEPT129', N'Business Center'),
    (N'DEPT130', N'HR Angola'),
    (N'DEPT131', N'OA'),
    (N'DEPT132', N'DI - Corporate Affairs'),
    (N'DEPT133', N'QAQC'),
    (N'DEPT134', N'TAX Department');

-- Insert only departments whose name or code is not already present
INSERT INTO [dbo].[Departments] ([Code], [Name], [Active])
SELECT d.[Code], LTRIM(RTRIM(d.[Name])), 1
FROM @Departments d
WHERE NOT EXISTS (
    SELECT 1
    FROM [dbo].[Departments] x
    WHERE x.[Name] = LTRIM(RTRIM(d.[Name]))
       OR x.[Code] = d.[Code]
);

SELECT @@ROWCOUNT AS RowsInserted;

COMMIT TRANSACTION;
GO